version: '3.8'
services:
  jenkins-server:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-lan
      - jenkins-wan
    environment:
      - JENKINS_JAVA_OPTS="-Djenkins.install.runSetupWizard=true"
    restart: always

  jenkins-agent:
    image: alpine:latest
    container_name: jenkins-agent
    networks:
      - jenkins-lan
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-server
    command: >
      /bin/sh -c "apk --no-cache add openjdk21-jre curl docker && tail -f /dev/null"
    restart: always

networks:
  jenkins-lan:
    driver: bridge

  jenkins-wan:
    driver: bridge

volumes:
  jenkins_home:
