apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-pvc
  namespace: gil-namespace
spec:
  accessModes:
    - ReadWriteMany   # Allows multiple pods to mount the same volume
  resources:
    requests:
      storage: 1Gi
